import time
import pytest
from TestCases.test_login import LoginPage
from PageObjects.MyInfoPage import Myinfo
from selenium import webdriver
from utilities.readProperties import ReadConfig
from utilities.customLogger import LogGen

logger = LogGen.loggen()

@pytest.fixture()
def drivers():
    driver = webdriver.Chrome()
    driver.maximize_window()
    driver.implicitly_wait(10)
    yield driver
    driver.close()
    driver.quit()

def test_myinfo(drivers):
    baseurl = ReadConfig.get_application_url()
    username = ReadConfig.get_username()
    password = ReadConfig.get_password()

    login_page = LoginPage(drivers)
    login_page.open_page(baseurl)
    time.sleep(1)
    login_page.user_name(username)
    time.sleep(1)
    login_page.pass_word(password)
    time.sleep(1)
    login_page.submit_button()
    time.sleep(2)
    logger.info("******** Login Successful *********")

    myinfo = Myinfo(drivers)
    myinfo.myinfo_page()
    time.sleep(1)
    myinfo.profile_picture("C:\Orange_HRM\wp2271188.jpg")
    time.sleep(3)
    myinfo.first_name("Cristiano")
    time.sleep(1)
    myinfo.middle_name("Ronaldo")
    time.sleep(1)
    myinfo.last_name("007")
    time.sleep(1)
    myinfo.employee_id("John")
    time.sleep(1)
    myinfo.other_id("12437")
    time.sleep(1)
    myinfo.license("56748")
    time.sleep(1)
    myinfo.license_expire("2023-20-10")
    time.sleep(1)
    myinfo.nationality_select()
    time.sleep(1)
    myinfo.martial_status()
    time.sleep(1)
    myinfo.date_of_birth("2001-15-10")
    time.sleep(1)
    myinfo.gender()
    time.sleep(1)
    myinfo.save()
    time.sleep(2)

    logger.info("******** Saved Personal details successful *********")

    myinfo.contact_details_page()
    time.sleep(1)
    myinfo.street_1("Anna")
    time.sleep(1)
    myinfo.street_2("3rd Street")
    time.sleep(1)
    myinfo.city("Chenn")
    time.sleep(1)
    myinfo.state("TN")
    time.sleep(1)
    myinfo.postal_code("345666")
    time.sleep(1)
    myinfo.country()
    time.sleep(1)
    myinfo.home("1234567891")
    time.sleep(1)
    myinfo.mobile("1234567891")
    time.sleep(1)
    myinfo.work("1234567891")
    time.sleep(1)
    myinfo.email("123@gmail.com")
    time.sleep(1)
    myinfo.other_email("321@gmail.com")
    time.sleep(1)
    myinfo.save_details_page()
    time.sleep(5)

    logger.info("******** Saved Contact details successful *********")

    myinfo.emergency_contact_page()
    time.sleep(1)
    myinfo.add_button()
    time.sleep(1)
    myinfo.add_name("Ronaldo")
    time.sleep(1)
    myinfo.add_relationship("Single")
    time.sleep(1)
    myinfo.add_home_number("1234567891")
    time.sleep(1)
    myinfo.add_mobile_number("9876543219")
    time.sleep(1)
    myinfo.save_emergency_contact()
    time.sleep(1)

    logger.info("******** Saved Emergency contact details successful *********")

    myinfo.immigration_page()
    time.sleep(1)
    myinfo.add_immigration()
    time.sleep(1)
    myinfo.add_passport()
    time.sleep(1)
    myinfo.add_number("9876543219")
    time.sleep(1)
    myinfo.issued_date("2022-6-24")
    time.sleep(1)
    myinfo.expiry_date("2034-6-24")
    time.sleep(1)
    myinfo.eligibility_status("Eligible")
    myinfo.issued_by()
    myinfo.eligible_review_date("2024-5-24")
    time.sleep(1)
    myinfo.save_immigration()
    time.sleep(3)
    myinfo.add_attachment()
    time.sleep(1)
    myinfo.browse_click("C:\Orange_HRM\sample_immigration.txt")
    time.sleep(2)
    myinfo.save_attachment()
    time.sleep(5)

    logger.info("******** Saved Immigration details successful *********")
    logger.info("******** Test My Info Page Completed *********")



